language: php


php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - phpenv config-rm xdebug.ini
  #- bash travis/$TRAVIS_PHP_VERSION.sh
  - bash travis/install_amqp.sh
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

script:
  - bin/atoum
