language: php

php:
  - 5.5
  - 5.6
  - 7.0

sudo: false

matrix:
  include:
    - php: 5.5
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.0
      env: COMPOSER_FLAGS="--prefer-stable" SYMFONY_VERSION=2.7.*
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini
  #- bash travis/$TRAVIS_PHP_VERSION.sh
  - bash travis/install_amqp.sh
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require symfony/symfony:${SYMFONY_VERSION} --no-update; fi

install: composer update --prefer-dist $COMPOSER_FLAGS

script: bin/atoum
