language: php

php:
  - 7.0
  - 7.1

env:
  - SYMFONY_VERSION="2.8.*"
  - SYMFONY_VERSION="3.1.*"
  - COMPOSER_FLAGS="--prefer-lowest"

matrix:
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini
  - bash travis/install_amqp.sh
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require symfony/symfony:${SYMFONY_VERSION} --no-update; fi

install: composer update --prefer-dist $COMPOSER_FLAGS

script: bin/atoum