language: php

php:
  - 5.5

before_script:
  - echo "extension = amqp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev

script:
  - bin/atoum
