language: php
sudo: false
cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_finish: true
    include:
        # Minimum supported dependencies with the latest and oldest PHP version
        - php: 7.4
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        - php: 7.0
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        # Test with specific Symfony (LTS) versions
        - php: 7.1
          env: SYMFONY_REQUIRE="3.4.*"
        - php: 7.2
          env: SYMFONY_REQUIRE="4.4.*"
        - php: 7.3
          env: SYMFONY_REQUIRE="5.*"
          # Latest commit to master
        - php: 7.4
          env: STABILITY="dev"
    allow_failures:
          # Dev-master is allowed to fail.
        - env: STABILITY="dev"

before_install:
  - phpenv config-rm xdebug.ini
  - bash travis/install_amqp.sh
  - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
  - composer global require --no-progress --no-scripts --no-plugins symfony/flex

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script: bin/atoum
