parameters:
    m6_web_amqp.exchange.class: 'M6Web\Bundle\AmqpBundle\Sandbox\NullExchange'
    m6_web_amqp.queue.class: 'M6Web\Bundle\AmqpBundle\Sandbox\NullQueue'
    m6_web_amqp.connection.class: 'M6Web\Bundle\AmqpBundle\Sandbox\NullConnection'
    m6_web_amqp.channel.class: 'M6Web\Bundle\AmqpBundle\Sandbox\NullChannel'
    m6_web_amqp.envelope.class: 'M6Web\Bundle\AmqpBundle\Sandbox\NullEnvelope'

