parameters:
    m6_web_amqp.connection.class : AMQPConnection
    m6_web_amqp.channel.class : AMQPChannel
    m6_web_amqp.exchange.class : AMQPExchange
    m6_web_amqp.queue.class: AMQPQueue
    m6_web_amqp.envelope.class: AMQPEnvelope
    
    m6_web_amqp.event.command.class: M6Web\Bundle\AmqpBundle\Event\Command

    m6_web_amqp.producer.class: M6Web\Bundle\AmqpBundle\Amqp\Producer
    m6_web_amqp.consumer.class: M6Web\Bundle\AmqpBundle\Amqp\Consumer

    m6_web_amqp.producer_factory.class: M6Web\Bundle\AmqpBundle\Factory\ProducerFactory
    m6_web_amqp.consumer_factory.class: M6Web\Bundle\AmqpBundle\Factory\ConsumerFactory

services:
    m6_web_amqp.producer_factory:
        class: "%m6_web_amqp.producer_factory.class%"
        arguments:
            - "%m6_web_amqp.channel.class%"
            - "%m6_web_amqp.exchange.class%"
            - "%m6_web_amqp.queue.class%"
            
    m6_web_amqp.consumer_factory:
        class: "%m6_web_amqp.consumer_factory.class%"
        arguments:
            - "%m6_web_amqp.channel.class%"
            - "%m6_web_amqp.queue.class%"
            - "%m6_web_amqp.exchange.class%"
