name: Continuous Integration
on: [push, pull_request]

jobs:
  tests-old-versions:
    name: Tests old versions
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php-version: ['7.4', '8.0', '8.1', '8.2' , '8.3' ]
      fail-fast: false
    steps:
      - uses: actions/checkout@master
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug2
          extensions: amqp-2
      - name: Install symfony v5.4
        env:
          SYMFONY_VERSION: '^5.4'
        run: composer require symfony/symfony:$SYMFONY_VERSION --no-update
      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction
      - name: Unit tests
        run: bin/atoum

  tests-current-versions:
    name: Tests current versions
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php-version: ['8.2' , '8.3' ]
        symfony-version: ['^6.4', '^7.0']
      fail-fast: false
    steps:
      - uses: actions/checkout@master
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          extensions: amqp-2
      - name: Install symfony version from matrix
        env:
          SYMFONY_VERSION: ${{ matrix.symfony-version }}
        run: composer require symfony/symfony:$SYMFONY_VERSION --no-update
      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction
      - name: Unit tests
        run: bin/atoum
